### PR TITLE
Change location of OutputWriter in FastMonodomainSolver

### PR DESCRIPTION
**Pull request by carme-hp**
**Motivation:** 
When running a solver consisting of the *FastMonodomainSolver* we were not able to create more than one output file. This is because the OutputWriter was called only once after the time for-loop. That was not a problem so far, because all existing cases using  *FastMonodomainSolver* were based on a coupled scheme. In such coupled schemes, we call the time for-loop for every coupling timestep and thus we were able to get multiple output files. 

**Changes:**
- new case with a non-coupled and a coupled example for  *FastMonodomainSolver*
-  modifications of the *FastMonodomainSolver* core files

- I've moved the  OutputWriter  from after the time for-loop to inside the time for-loop. I considered keeping the call to the OutputWriter but removed it because in the coupled case it leads to twice the expected number of output files. In any case, having an extra call to OuputWriter after the time for-loop should not be necessary, since nothing is calculated since the last call.  *Do we need the call after the time for-loop  to match the number of files with another solver?* 

- To write the output files we have to call the function  `updateFiberData()` before hand, so I also moved this one into the time for-loop. In order to save compute time I only do it for the time steps where we will have output. 

```
    if (withOutputWritersEnabled){
      if (timeStepNo%timeStepOutputInterval == 0){
        updateFiberData();
        callOutputWriter(timeStepNo,currentTime, nTimeStepsSplitting_);
      }
    }
```

> **Warning**
> There are some things are still not fully clear to me and I don't know to which point are problematic. The number of ouput files is controlled by the setting `"timeStepOutputInterval": ` in StrangSplitting. The example case is given such that there is an output file for every `dt_elasticity`.
 > The problem is that for the coupled case, even if we choose a very large `"timeStepOutputInterval": `, we will still get an output file every  coupling timestepwidth `dt_elasticity`. It looks like we can only tune it to get more output but not to get less output.

### CODE REVIEW

**Comment by erikscheurer** [comment]
Compiling an example (`examples/electrophysiology/neuromuscular/surface_coupling/muscle_tendon`) from the `two_muscles_with_precice` branch with these changes fails at [`core/src/control/precice/surface_coupling/00_nested_solver.tpp#L153`](https://github.com/maierbn/opendihu/blob/760cd422c502684b34fffacadcc43449f577fb1f/core/src/control/precice/surface_coupling/00_nested_solver.tpp#L153) at the function `load_fiber_state()` saying that such a method doesn't exist for `class FastMonodomainSolver<...>`
<details>

```
pcsgs02:[muscle_tendon] >sr
scons: Reading SConscript files ...
Checking for MPI ...           (cached) yes
Checking for PETSc ...         (cached) yes
Checking for Python 3.9 ...    (cached) yes
Checking for Python packages...(cached) yes
Checking for Base64 ...        (cached) yes
Checking for googletest ...    (cached) yes
Checking for SEMT ...          (cached) yes
Checking for ADIOS2 ...        (cached) yes
Checking for Vc ...            (cached) yes
Checking for std_simd ...      (cached) yes
Checking for xbraid ...        (cached) yes
Checking for OpenCOR ...       (cached) yes
Checking for libxml2 ...       (cached) yes
Checking for preCICE ...       (cached) yes
Checking for EasyLogging++ ... (cached) yes
Compilers: C: gcc, C++: g++, MPI: mpic++
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build_release
Compiling src/muscle_neuromuscular.cpp
In file included from /data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/00_nested_solver.h:238,
                 from /data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/01_initialize.h:5,
                 from /data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/02_read_write.h:5,
                 from /data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/03_checkpoint.h:5,
                 from /data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/precice_adapter.h:6,
                 from /data/scratch/scheurek/software/opendihu/core/src/opendihu.h:14,
                 from src/muscle_neuromuscular.cpp:4:
/data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/00_nested_solver.tpp: In instantiation of ‘void Control::PreciceAdapterNestedSolver<Control::Coupling<T1, MuscleContractionSolver<T2, T3> > >::saveFiberData(Control::PreciceAdapterNestedSolver<Control::Coupling<T1, MuscleContractionSolver<T2, T3> > >::NestedSolverType&) [with T1 = FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >; T2 = Mesh::StructuredDeformableOfDimension<3>; T3 = Equation::SolidMechanics::TransverselyIsotropicMooneyRivlinIncompressibleActive3D; Control::PreciceAdapterNestedSolver<Control::Coupling<T1, MuscleContractionSolver<T2, T3> > >::NestedSolverType = Control::Coupling<FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >, MuscleContractionSolver<Mesh::StructuredDeformableOfDimension<3> > >]’:
/data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/precice_adapter.tpp:72:7:   required from ‘void Control::PreciceAdapter<NestedSolver>::run() [with NestedSolver = Control::Coupling<FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >, MuscleContractionSolver<Mesh::StructuredDeformableOfDimension<3> > >]’
src/muscle_neuromuscular.cpp:87:15:   required from here
/data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/00_nested_solver.tpp:145:32: error: ‘class FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >’ has no member named ‘saveFiberState’
  145 |   nestedSolver.timeStepping1().saveFiberState();
/data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/00_nested_solver.tpp: In instantiation of ‘void Control::PreciceAdapterNestedSolver<Control::Coupling<T1, MuscleContractionSolver<T2, T3> > >::loadFiberData(Control::PreciceAdapterNestedSolver<Control::Coupling<T1, MuscleContractionSolver<T2, T3> > >::NestedSolverType&) [with T1 = FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >; T2 = Mesh::StructuredDeformableOfDimension<3>; T3 = Equation::SolidMechanics::TransverselyIsotropicMooneyRivlinIncompressibleActive3D; Control::PreciceAdapterNestedSolver<Control::Coupling<T1, MuscleContractionSolver<T2, T3> > >::NestedSolverType = Control::Coupling<FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >, MuscleContractionSolver<Mesh::StructuredDeformableOfDimension<3> > >]’:
/data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/precice_adapter.tpp:105:7:   required from ‘void Control::PreciceAdapter<NestedSolver>::run() [with NestedSolver = Control::Coupling<FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >, MuscleContractionSolver<Mesh::StructuredDeformableOfDimension<3> > >]’
src/muscle_neuromuscular.cpp:87:15:   required from here
/data/scratch/scheurek/software/opendihu/core/src/control/precice/surface_coupling/00_nested_solver.tpp:153:32: error: ‘class FastMonodomainSolver<Control::MultipleInstances<OperatorSplitting::Strang<Control::MultipleInstances<TimeSteppingScheme::Heun<CellmlAdapter<9, 19, FunctionSpace::FunctionSpace<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1> > > > >, Control::MultipleInstances<TimeSteppingScheme::ImplicitEuler<SpatialDiscretization::FiniteElementMethod<Mesh::StructuredDeformableOfDimension<1>, BasisFunction::LagrangeOfOrder<1>, Quadrature::Gauss<2>, Equation::Dynamic::IsotropicDiffusion> > > > > >’ has no member named ‘loadFiberState’
  153 |   nestedSolver.timeStepping1().loadFiberState();
scons: *** [build_release/src/muscle_neuromuscular.o] Error 1
scons: building terminated because of errors.

real    0m15.543s
user    0m14.949s
sys     0m0.617s
release build failed
```

</details>

**Comment by carme-hp** [comment]
Good point. This means I cannot merge it directly. I added the function `load_fiber_state` and `save_fiber_state` some weeks ago (in relation to #5 ). But they are experimental changes, so I will remove it from the [two_muscles_with_precice](https://github.com/maierbn/opendihu/tree/two_muscles_with_precice) branch.

**Comment by IshaanDesai** [comment]
Just had a quick look at the changes and the PR seems to touch many things which are not directly related to file output. Is this intended? Also the added call to `updateFiberData` before adding the additional output made me wonder why a data update would be necessary.

**Comment by carme-hp** [comment]
I took a look at the files that are modified and it's all consistent. I just removed some experimental functions related to the fibers solver, that's why there are modifications to unexpected files (eg. on the precice part).

The `updateFiberData()` was already call before plotting before this pull request. The motivation is that the calculations are not made directly in the FiberData structucture, which is what is used for plotting. 

I have made a new commit because I look at the content of the output files and the diffusion was not looking good, but now it should be fine. I now use the setting `"setSpecificStatesRepeatAfterFirstCall":  0.01` for the reaction part. I took this value from the surface coupling examples, and I'm not sure if this is the best choice for this case. 

> **Note**
> I do know that using `"setSpecificStatesRepeatAfterFirstCall":  variables.end_time` leads to different results with the coupled and the non-coupled case. The coupled case looks like in the 0.01 case, but the non-coupled case looks like we stimulate it longer (but only up to 5.0, yet ènd_time = 20`. 

The problem mentioned above about the number of output files being limited by the coupling timestepwidth still holds.

Also tests are not passing, so I don't want to merge it yet (it may be I need to change the tests according to this pr). In any case I still think that the content of this pr can be used already by @erikscheurer .

**Comment by maierbn** [comment]
> * 
> 
> * I've moved the  OutputWriter  from after the time for-loop to inside the time for-loop. I considered keeping the call to the OutputWriter but removed it because in the coupled case it leads to twice the expected number of output files. In any case, having an extra call to OuputWriter after the time for-loop should not be necessary, since nothing is calculated since the last call.  _Do we need the call after the time for-loop  to match the number of files with another solver?_

Discouraged, as noted in #9.

**Comment by maierbn** [comment]
You know the semantics of `setSpecificStatesRepeatAfterFirstCall`, right?
image
Settings it to `end_time` would be unphysiological (or reach into the socket). A value of 0.01 ms is usually fine, if you get "missed" spikes, increase it a little bit.

**Pull request closed without merging**
