### PR TITLE
Docker ubuntu16 18

### PR DESCRIPTION
**Pull request by maierbn**
Adding docker files for ubuntu 16.04 and 18.04. I try to get them working.
- [x] build and upload docker image for ubuntu16
- [x] build and upload docker image for ubuntu18

### CODE REVIEW

**Comment by maierbn** [comment]
# ubuntu 16.04
* ADIOS2 fails because of `CMake 3.6 or higher is required.  You are running version 3.5.1`
* precice fails because of: `CMake 3.16.3 or higher is required.  You are running version 3.5.1`

# ubuntu 18.04
* precice fails because of: `CMake 3.16.3 or higher is required.  You are running version 3.10.2`

**Comment by carme-hp** [comment]
@maierbn are you using petsc 3.12 or 3.15?
I see that the errors are not petsc related but I was wondering if we should keep a branch with petsc 3.12 to create the docker images for ubuntu 16 and 18

**Comment by maierbn** [comment]
I use petsc 3.15. And currently rebuilding with newer cmake.

**Comment by carme-hp** [comment]
Hi, 
I was looking through the [preCICE documentation](https://precice.org/installation-source-dependencies.html#ubuntu-1804-bionic-beaver) and it says that the last version of precice to support ubuntu 18 is precice v2.3
This could be the source for the current problems since I updated precice from v2.1 to v2.5

**Comment by maierbn** [comment]
I get linker errors in precice (in both ubuntu 16 and 18):
` error while loading shared libraries: libboost_log_setup.so.1.83.0: cannot open shared object file: No such file or directory
`
Apart from that everything works (petsc gets installed with all dependencies)

**Comment by maierbn** [comment]
I don't understand it
```
g++ -o a.out -pthread -Wl,-rpath -Wl,/usr/lib/openmpi/lib -Wl,--enable-new-dtags -Wl,-rpath=/workspace/opendihu/dependencies/petsc/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/python/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/base64/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/googletest/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/semt/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/adios/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/vc/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/std_simd/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/xbraid/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/opencor/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/libxml2/install/lib -Wl,-rpath=/workspace/opendihu/dependencies/precice/install/lib .sconf_temp/conftest_12.o -L/workspace/opendihu/dependencies/precice/install/lib -L/usr/lib/openmpi/lib -Ldependencies/petsc/install/lib -Ldependencies/python/install/lib -Ldependencies/base64/install/lib -Ldependencies/googletest/install/lib -Ldependencies/semt/install/lib -Ldependencies/adios/install/lib -Ldependencies/vc/install/lib -Ldependencies/std_simd/install/lib -Ldependencies/xbraid/install/lib -Ldependencies/opencor/install/lib -Ldependencies/libxml2/install/lib -Ldependencies/precice/install/lib -lboost_log_setup -lprecice -lxml2 -lbraid -lVc -ladios2 -lgtest -lpython3.9 -lcmumps -lHYPRE -lpetsc -lscalapack -lparmetis -ldmumps -lsmumps -lzmumps -lmumps_common -lcmumps -lscalapack -lpetsc -lpord -lparmetis -lpetsc -ldmumps -lpetsc -lsmumps -lmpi_cxx -lmpi -lm ; ./a.out
./a.out: error while loading shared libraries: libboost_log_setup.so.1.83.0: cannot open shared object file: No such file or directory
```
The library `/workspace/opendihu/dependencies/precice/install/lib/libboost_log_setup.so.1.83.0` exists and is readable.

```
LD_LIBRARY_PATH=/workspace/opendihu/dependencies/precice/install/lib:/workspace/opendihu/dependencies/petsc/install/lib ./a.out
```
This works but how to tell the linker to include the library path in rpath? I thought it did everything needed.

**Comment by maierbn** [comment]
Now I disabled precice in the Dockerfiles for ubuntu 16 and 18, I think it is fine. You can merge if you want to.

**Comment by maierbn** [comment]
Then, `--branch docker-ubuntu16-18` needs to be adjusted/removed in the Dockerfiles.

**Pull request merged**
